[package]
name = "absorber"
version = "0.1.0"
authors = ["Chris Whealy <chris@whealy.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
num-complex = "^0.2"
num-format = "^0.4.0"
num = "^0.2.0"
libm = "^0.1.4"
serde = "^1.0.59"
serde_derive = "^1.0.59"

[dependencies.wasm-bindgen]
version = "^0.2"
features = ["serde-serialize"]

[dependencies.web-sys]
version = "^0.3.4"
features = [
  'ImageData'
, 'CanvasRenderingContext2d'
, 'TextMetrics'
, 'Document'
, 'Element'
, 'HtmlCanvasElement'
, 'Window'
]