[package]
name = "porous_absorber_calculator"
version = "0.4.1"
authors = ["Chris Whealy <chris@whealy.com>"]
edition = "2018"
description = "Calculates the acoustic absorption curve of various porous absorber systems"

[lib]
crate-type = ["cdylib"]

[dependencies]
num-complex = "^0.2"
num-format = "^0.4.0"
num = "^0.2.0"
libm = "^0.1.4"
serde = { version = "^1.0.59", features = ["derive"] }
serde_derive = "^1.0.59"

[dependencies.wasm-bindgen]
version = "^0.2"
features = ["serde-serialize"]

[dependencies.web-sys]
version = "^0.3.4"
features = [
  'ImageData'
, 'CanvasRenderingContext2d'
, 'TextMetrics'
, 'Document'
, 'Element'
, 'HtmlCanvasElement'
, 'Window'
]